FROM docker.io/jboss/keycloak:latest

# Turn of caching in the configuration so we can modify the theme and refresh to see changes
COPY ./resources/standalone.xml /opt/jboss/keycloak/standalone/configuration/standalone.xml

# Set up a JOSA realm
COPY ./resources/josa-realm.json /tmp/josa-realm.json

# Copy the theme in, though this content will be overridden if you mount the folder when running
COPY ./josa_theme/ /opt/jboss/keycloak/themes/josa_theme/
